@startuml

actor DocumentConsumer

component "Document Registry" as DocumentRegistry
component "Document Repository" as DocumentRepository
component "Image Repository" as ImageRepository

interface "Query for patient image and/or report" as IC
interface "Retrieve selected imaging report" as IC2
interface "Retrieve selected imaging study (and image instances)" as IC3

DocumentConsumer --> IC
IC --> DocumentRegistry

DocumentConsumer --> IC2
IC2 --> DocumentRepository

DocumentConsumer --> IC3
IC3 --> ImageRepository

@enduml
