@startuml

skinparam svgDimensionStyle false

title Radiology Integration


component ClientApplication

  component "Image Repository" as PACSRepository
   component "Document Repository" as DocumentRepository


interface "Imaging Study \nor Report Interface" as ImagingStudyInterface
note right
Entity Model Imaging Study [[https://www.dicomstandard.org/News-dir/ftsup/docs/sups/sup59.pdf DICOM KOS]] or [[StructureDefinition-ImagingReport.html Imaging Report]]
Interface Contract [[https://profiles.ihe.net/ITI/MHD/ITI-68.html IHE Mobile access to Health Documents (MHD) \nRetrieve Document ITI-68]]
end note

interface "Image Interface" as ImageInterface
note right
Entity Model [[https://www.dicomstandard.org DICOM]]
Interface Contract [[https://wiki.ihe.net/index.php/Web-based_Image_Access IHE Web-based Image Access]]
end note

ClientApplication -d- ImagingStudyInterface
ClientApplication -d- ImageInterface

ImagingStudyInterface -d- DocumentRepository
ImageInterface -d- PACSRepository

@enduml
