@startuml

skinparam svgDimensionStyle false

title "Document Entry Category and Type (Extract)"



note "Both IHE and HL7 FHIR allow multiple category and class codes\n\nThese codes are used by users for searching for a documents.\n\nThe use of type appears to be like a name" as N1

json "[[ValueSet-document-entry-class.html DocumentCategory]]" as Category {
  "734163000":"Care plan"
}


json "[[https://fhir.ch/ig/ch-term/3.0.0/ValueSet-DocumentEntry.typeCode.html Switzerland Document Type (Care Plan only)]]" as Type {
  "737427001":"Clinical Management Plan",
  "773130005":"Nursing Care Plan",
  "736055001":"Rehabilitation care plan",
  "419891008":"Record artifact"
}

note "This may be useful as a sub-category to aid searching" as N2

N2 .u. Type


json "[[ValueSet-nrl.document-entry-type.html NRL Document Type (Care Plan only)]]" as Composition {
 "736253002":"Mental health crisis plan",
 "887701000000100":"Emergency health care plan",
 "861421000000109":"End of life care coordination summary",
 "736373009":"End of life care plan",
 "1382601000000107" :"ReSPECT (Recommended Summary Plan for \nEmergency Care and Treatment) form",
 "325691000000100":"Contingency plan",
 "735324008":"Treatment escalation plan",
 "736366004":"Advance care plan"
}

json "[[ValueSet-scotland.document-entry-type.html Scotland/PRSB Document Type (Care Plan only)]]" as Scotland {
 "823581000000101":"Multidisciplinary Care Plan",
 "736372004":"Discharge Care Plan",
 "736373009":"End of Life Care Plan",
 "962891000000106":"Individualised Treatment Guideline",
 "1382601000000107":"ReSPECT (Recommended Summary Plan for \nEmergency Care and Treatment) form",
 "734163000":"Care plan"
}

class "UKCore Document Type" as UKCoreDocumentType <<value>> {
  [[https://simplifier.net/HL7FHIRUKCoreR4/ValueSet-UKCore-DocumentType UKCore DocumentType]] [[https://termbrowser.nhs.uk/?perspective=full&conceptId1=999001111000000105&edition=uk-edition&release=v20240731&server=https://termbrowser.nhs.uk/sct-browser-api/snomed&langRefset=999001261000000100,999000691000001104 Refset 999001111000000105]]
}


Category -- Type : parent-child
Category -- Composition
Category -- Scotland
Category -- UKCoreDocumentType

Scotland -d[hidden]- Type
UKCoreDocumentType -d[hidden]- Composition
@enduml
