@startuml

skinparam svgDimensionStyle false

package healthdocuments as "Radiology" {

  entity "[[StructureDefinition-DiagnosticReport.html Diagnostic Report]]" as diagnosticReport  <<aggregate root>>  {
    identifier
    subject : PatientIdentifier
    performer [organisation] :OrganisationIdentifier
    performer [primary reporter]:   PractitionerIdentifier
    performer [secondary reporter]:   PractitionerIdentifier
    performer [technician]:   PractitionerIdentifier
    category: [[https://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_29.html Modality]]
    code: [[https://www.datadictionary.nhs.uk/data_elements/imaging_code__nicip_.html IMAGING CODE (NICIP)]]
    effectiveDateTime
    encounter: EncounterIdentifier
    attachment : Attachment
    basedOn: ServiceRequestIdentifier
  }

  entity "Attachment" as attachment <<entity>> {
    url
    data
    }

  entity "[[StructureDefinition-Document.html Document]]" as Document <<entity>> {
  }



}


package Workflow {
  class "[[StructureDefinition-accession-number.html ServiceRequestIdentifier]]" as ServiceRequestIdentifier {
  }
}

package PatientAdministration as "Patient Administration" {


  class "[[StructureDefinition-patient-identifier.html PatientIdentifier]]" as PatientIdentifier <<value>> {
  }



  class EncounterIdentifier <<value>> {
    identifier
  }

  PatientIdentifier -d[hidden]- EncounterIdentifier
}


package directories as "Care Directories" {

class "[[StructureDefinition-organisation-identifier.html OrganisationIdentifier]]" as OrganisationIdentifier <<value>> {
}

class "[[StructureDefinition-practitioner-identifier.html PractitionerIdentifier]]" as PractitionerIdentifier <<value>>  {
}

  OrganisationIdentifier -d[hidden]- PractitionerIdentifier

}


  diagnosticReport o--> attachment

  attachment o--> Document : data


  diagnosticReport -d-> PatientIdentifier : subject
  diagnosticReport o--> EncounterIdentifier: encounter
  diagnosticReport o-d-> OrganisationIdentifier : performer [organisation]
  diagnosticReport o--> PractitionerIdentifier: performer [reporter and technician]
  diagnosticReport o--> ServiceRequestIdentifier: basedOn


@enduml
