@startuml

skinparam svgDimensionStyle false

package healthdocuments as "Health Documents" {

  entity "[[StructureDefinition-DocumentIndex.html Document Index]]" as document  <<aggregate root>>  {
    identifier
    subject : [[StructureDefinition-Patient.html PatientIdentity]]
    custodian: [[StructureDefinition-Organisation.html OrganisationIdentity]]
    author: [[StructureDefinition-Organisation.html OrganisationIdentity]] or [[StructureDefinition-Practitioner.html PractitionerIdentifier]]
    category: DocumentClass
    type: DocumentType
    facilityType: [[ValueSet-facility-type.html FacilityType]]
    practiceSetting: [[ValueSet-specialty.html Specialty]]
    period : Period
    encounter: [[StructureDefinition-EncounterEvent.html EncounterIdentity]]
    attachment : [[StructureDefinition-Document.html Document]]
    eventCode: [[ValueSet-service.html Service]]
    Finding and Retrieving Documents() : [[CapabilityStatement-NHSE-CIC-8-IPA.html CIC-8-IPA]] [[CapabilityStatement-NHSE-CIC-8-MHD.html CIC-8-MHD]]
    Finding and Retrieving Images() : [CIC-11]
    Sending Document Event Notifications() : [[CapabilityStatement-NHSE-CIC-21-Event.html CIC-21]]
    Transfer document/images between systems() : [CIC-18]
  }


  abstract "[[StructureDefinition-Document.html Document]]" as Document {
  }

   class "[[ValueSet-document-index-class.html DocumentClass]]" as DocumentClass <<value>> {
    }

  class "[[ValueSet-document-index-type.html DocumentType]]" as DocumentType <<value>> {

  }


    DocumentClass o-d-> DocumentType : parent of

}




package PatientAdministration as "[[subdomain-patient-administration.html Patient Administration]]" {



  class  "[[StructureDefinition-Patient.html PatientIdentity]]" as PatientIdentity <<value>> {
    id
    [[https://www.datadictionary.nhs.uk/data_elements/nhs_number.html NHS Number]] : 0..1 Identifier
    Medical Record Numbers : 0..* Identifier
  }



  class "[[StructureDefinition-EncounterEvent.html EncounterIdentity]]" as EncounterIdentity <<value>> {
    identifier
  }

  PatientIdentity -d[hidden]- EncounterIdentity
}


package directories as "[[subdomain-care-directories.html Care Directories]]" {

class "[[StructureDefinition-Organisation.html OrganisationIdentity]]" as OrganisationIdentity <<value>> {
  [[https://www.datadictionary.nhs.uk/attributes/organisation_code.html ORGANISATION CODE]] : ODS Code
}

class "[[StructureDefinition-Practitioner.html PractitionerIdentifier]]" as PractitionerIdentifier <<value>>  {
id: SDS User Id [NHS E internal use only?]
identifier: GMP, GMC, HPCC, NMC, etc
}

  OrganisationIdentity -d[hidden]- PractitionerIdentifier

}



  document o--> DocumentClass
  document o--> DocumentType


  document o--> Document

document -d-> PatientIdentity : subject
  document --> EncounterIdentity: encounter
  document -d-> OrganisationIdentity : custodian and author
  document --> PractitionerIdentifier: author
  document --> Specialty: practiceSetting

@enduml
